/*
Section 1: Getting Started 

Intro to Rust 

What is Rust 
•Systems programming- languages optimized for situations when memory and CPU resources are limited 
•Resources = memory & CPU 
•Very stable and safe language 
•Works on PC, MacOS, and Linux


What Can Rust Build 
•Command line programs, drivers, databases, operating systems 
•Very versatile 


The Rust Compiler 
•Source code- code written by devs, meant to be readable by humans 
•Rust code itself cannot be understood by the computed 
•Rust compiler- translates rust source code into executable binary program 
•Compiler = translator 


Syntax 
•Characters & symbols devs use to write source code 
•Each programming language can be different 
•Rust is VERY strict 


macOS Intro to Terminal 
•Terminal- command line interface, text prompt where you can enter commands for the computer to execute 
•pwd- print working directory 
    •Print- output to screen 
    •Working directory- folder you are currently in 
•ls- list, lists all files and folders in current directory 
•cd- change directory, lets you navigate into a directory 
•Must honor case sensitivity of directory and file names 
•Tab key autocompletes 


Add VSCode to PATH 
•Cmd + Shift + P opens VSCode pallet, which acts like a terminal 
•Shell Command Install ‘code’ command in PATH- added VSCode to terminal, allows us to use ‘code .’ Command 
 

Windows Intro to Powershell 
•Powershell- command line 
•Pwd- print working directory 


Updating or Uninstalling Rust with rustup 
•rustup- was installed when installing rust compiler 
•Runs from command line, will give you other commands you can use 
•‘rustup’ followed by chosen command 

 
Install Git 
•git init- create a new repo 
•git status- shows which changes have been staged, which haven't, and which files aren't being tracked 
•git add- moves changes from your working directory into the staging area 
•git commit- captures a snapshot of your project's currently staged changes and permanently records it to the version control history 
•git checkout- used to switch between branches, create new branches, navigate to specific commits, and discard local changes 
•git restore- used to discard uncommitted changes in your working directory or staging area 


Create Rust Project with Cargo 
•Cargo- command line tool that helps manage Rust projects 
    •Create, compile, format, etc. 
    •Best way to create a new rust project, provides starter template 
•cargo new project_name 
    •No spaces 
    •snake_case 
•cammelCase 
•Rust projects also called packages or crates 
•2 types of rust packages/crates 
    •Binary crate- independent rust app whose purpose is to be run by itself in isolation
        •Car 
    •Library crate- rust app that will be incorporated by other binary crates 
        •Tire, or engine 
        •Value is in being applied to other places 
•.rs- file type for rust files 
•Target directory- when code is compiles, the executable will go to the target folder 
•Executable- resulting program that comes from compiling source code 
•gitignore file- tells git which files to ignore 
•cargo.toml file- stores info and metadata that can be updated and customized later 
•toml file- place to store keys and values 
•cargo.lock file- automatically created when you compile code, do NOT edit this file manually. Tracks independencies 


Rust Functions
•Function- procedure, sequence of instructions to execute in order 
    •Like a cooking recipe 
•Can be many functions in a single rust program 
•Functions exist to organize code 
•Each function should have its own responsibility 
•fn- function key word, declares a function 
*/
fn function_name (parameters) {  
    code block
} 
/*
•All rust programs must have a fn main ( ) { } 
    •Entry point to the program 
    •Main will automatically be executed first 
•Calling/invoking a function- executing a function 
•Functions must be performed by fn main ( ) or called by another function that is then called by fn main ( ) 
    •Similar to COBOL 
*/
fn main() { 
    function_to_be_called(); 

} 

/*

 */